# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  app

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 180
    Environment:
      Variables:
        STORAGE_TABLE: !Ref TodoAppTable
        SALT: 10

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:

  #
  # TABLE
  #

  TodoAppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      TableName: "TodoAppTable"
      KeySchema: 
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE" 
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  #
  # AUTH FUNCTIONS
  #
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/auth/signup/
      Handler: index.handler
      Description: Signup to the todo application
      Policies:
        # Give Create/Read/Update/Delete permission for db
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoAppTable
      Layers: 
        - !Ref LibraryLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth/signup
            Method: POST

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/auth/login/
      Handler: index.handler
      Description: Login to the todo application
      Policies:
        # Give Create/Read/Update/Delete permission for db
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoAppTable
      Layers: 
        - !Ref LibraryLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST

  ResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/auth/reset/
      Handler: index.handler
      Description: Reset password to the todo application
      Policies:
        # Give Create/Read/Update/Delete permission for db
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoAppTable
      Layers: 
        - !Ref LibraryLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth/reset
            Method: POST

  ForgotPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/auth/forgot/
      Handler: index.handler
      Description: Forgot password to the todo application
      Policies:
        # Give Create/Read/Update/Delete permission for db
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoAppTable
      Layers: 
        - !Ref LibraryLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth/forgot
            Method: POST

  #
  # ITEM FUNCTIONS
  #

  #
  # LAYER
  #

  # Layer with libraries and helpers 
  LibraryLayer: 
    Type: AWS::Serverless::LayerVersion
    Properties: 
      LayerName: todo-app-dependencies
      Description: Libraries and helper functions for Todo app. 
      ContentUri: src/layers/
      CompatibleRuntimes: 
        - nodejs14.x
      RetentionPolicy: Retain

Outputs:
  AuthAppApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  